- title: NCBI Entrez
  db: entrez
  id: Gene ID
  ref_url: "https://www.ncbi.nlm.nih.gov/gene/101954267"
  ref_id: "101954267"
  bad_ids:
  - id: "d101954267"
    reason: contains letter
  - id: "10195426700"
    reason: too long
  data_tags:
    ids: ["101954267", "105369219"]
    tags:
    - name: symbol
      values: [RNVU1-15, LOC105369219]
    - name: location
      values: [1q21.1, 20p13]
    - name: description
      values:
       - "RNA, variant U1 small nuclear 15"
       - "uncharacterized LOC105369219"

- title: PubMed
  db: pubmed
  id: PMID
  ref_url: "https://www.ncbi.nlm.nih.gov/pubmed/20345488"
  ref_id: "20345488"
  bad_ids:
    - id: "pmc20345488"
      reason: contains letters
    - id: "22"
      reason: too short
    - id: "203454880"
      reason: too long
  data_tags:
    ids: ["20345488", "20600793"]
    tags:
    - name: year
      values: ["2010", "2010"]
    - name: journal
      values:
        - Cellular microbiology
        - Microbial pathogenesis
    - name: title
      values:
       - The Anaplasma phagocytophilum-occupied vacuole selectively recruits Rab-GTPases that are predominantly associated with recycling endosomes.
       - Anaplasma phagocytophilum APH_0032 is expressed late during infection and localizes to the pathogen-occupied vacuolar membrane.

- title: KEGG Pathway
  db: kegg
  id: KEGG ID
  ref_url: "http://www.genome.jp/dbget-bin/www_bget?pathway:hsa04915"
  ref_id: "hsa04915"

- title: Gene Ontology
  db: go
  id: GO
  ref_url: "http://amigo.geneontology.org/amigo/term/GO:0042417"
  ref_id: "GO:0042417"
  bad_ids:
    - id: "0042417"
      reason: missing prefix
  data_tags:
    ids: ["GO:0042417", "GO:0044444"]
    tags:
    - name: name
      values:
        - dopamine metabolic process
        - cytoplasmic part
    - name: definition
      values:
        - The chemical reactions and pathways involving dopamine, a catecholamine neurotransmitter and a metabolic precursor of noradrenaline and adrenaline.
        - Any constituent part of the cytoplasm, all of the contents of a cell excluding the plasma membrane and nucleus, but including other subcellular structures.

- title: CRAN Package
  db: cran
  id: name
  ref_url: "https://cran.r-project.org/package=ggplot2"
  ref_id: "ggplot2"
  bad_ids:
    - id: "2ggplot"
      reason: must start with a letter
    - id: "ggplot2."
      reason: can't end with a period
    - id: "ggplot$2"
      reason: only letters, numbers and periods

- title: Bioconductor Package
  db: bioc
  id: name
  ref_url: "https://bioconductor.org/packages/Biobase"
  ref_id: "Biobase"
